export const FETCH_PRODUCTS_BY_CATEGORIES_REQUEST = 'FETCH_PRODUCTS_BY_CATEGORIES_REQUEST';
export const FETCH_PRODUCTS_BY_CATEGORIES_SUCCESS = 'FETCH_PRODUCTS_BY_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_BY_CATEGORIES_FAILED = 'FETCH_PRODUCTS_BY_CATEGORIES_FAILED';

export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETIALS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAILED = 'FETCH_PRODUCT_DETAILS_FAILED';
