export const ADD_MEASUREMENTS_REQUEST = 'ADD_MEASUREMENTS_REQUEST';
export const ADD_MEASUREMENTS_SUCCESS = 'ADD_MEASUREMENTS_SUCCESS';
export const ADD_MEASUREMENTS_FAILED = 'ADD_MEASUREMENTS_FAILED';