export const screens = {
  bottomTabs: 'bottomTabs',
  mainStack: 'mainStack',
  designerStack: 'designerStack',
  categoryStack: 'categoryStack',
  brandStack: 'brandStack',
  authStack: 'authStack',
  cartStack: 'cartStack',

  profile: 'Profile',
  auth: 'Auth',
  home: 'Home',
  category: 'Category',
  brands: 'Outlets',
  categorydetail: 'CategoryDetail',
  cart: 'Cart',
  designers: 'Designers',
  designerdetail: 'DesignerDetails',
  productDetails:'ProductDetails',
  resetemail: 'ResetEmail',
  resetpassword: 'ResetPassword',
  otp: 'Otp',
  profilesection: 'ProfileSection',
  shippingaddress: 'ShippingAddress',
  payment: 'Payment',
  creditinfo: 'CreditInfo',

  step1: 'step1',
  step2: 'step2',
  step3: 'step3',
  sideMenu: 'sideMenu',
  recommendations: 'Recommendations',
  searchresult: 'SearchResult',
  filterresult: 'FilterResult',
  sortresult: 'SortResult',
  webView: 'webView',
};